name: Wheatland Mission
favicon: null
layout_spectrum: 0.37083
typography_spectrum: 0.91351
title: "Wheatland Mission Church —\_Wichita, KS"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b1492e'
    - '#d7a193'
    - '#c57764'
    - '#d3c3c0'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
